# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefa.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tarefa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctarefa.proto\"y\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x04 \x01(\t\x12\x17\n\x06status\x18\x05 \x01(\x0e\x32\x07.Status\x12\x14\n\x0cresponsaveis\x18\x06 \x03(\t\"y\n\x12\x43riarTarefaRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x03 \x01(\t\x12\x17\n\x06status\x18\x04 \x01(\x0e\x32\x07.Status\x12\x14\n\x0cresponsaveis\x18\x05 \x03(\t\"\x0e\n\x0cListaRequest\"&\n\nListaReply\x12\x18\n\x07tarefas\x18\x01 \x03(\x0b\x32\x07.Tarefa\"M\n\x10\x41tualizacaoReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x17\n\x06tarefa\x18\x03 \x01(\x0b\x32\x07.Tarefa\"\x1c\n\x0eRemoverRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x0cRemoverReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t*7\n\x06Status\x12\x0c\n\x08PENDENTE\x10\x00\x12\x10\n\x0c\x45M_ANDAMENTO\x10\x01\x12\r\n\tCONCLUIDO\x10\x02\x32\xcc\x01\n\x10GerenciarTarefas\x12+\n\x0b\x43riarTarefa\x12\x13.CriarTarefaRequest\x1a\x07.Tarefa\x12+\n\rListarTarefas\x12\r.ListaRequest\x1a\x0b.ListaReply\x12-\n\x0f\x41tualizarTarefa\x12\x07.Tarefa\x1a\x11.AtualizacaoReply\x12/\n\rRemoverTarefa\x12\x0f.RemoverRequest\x1a\r.RemoverReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=477
  _globals['_STATUS']._serialized_end=532
  _globals['_TAREFA']._serialized_start=16
  _globals['_TAREFA']._serialized_end=137
  _globals['_CRIARTAREFAREQUEST']._serialized_start=139
  _globals['_CRIARTAREFAREQUEST']._serialized_end=260
  _globals['_LISTAREQUEST']._serialized_start=262
  _globals['_LISTAREQUEST']._serialized_end=276
  _globals['_LISTAREPLY']._serialized_start=278
  _globals['_LISTAREPLY']._serialized_end=316
  _globals['_ATUALIZACAOREPLY']._serialized_start=318
  _globals['_ATUALIZACAOREPLY']._serialized_end=395
  _globals['_REMOVERREQUEST']._serialized_start=397
  _globals['_REMOVERREQUEST']._serialized_end=425
  _globals['_REMOVERREPLY']._serialized_start=427
  _globals['_REMOVERREPLY']._serialized_end=475
  _globals['_GERENCIARTAREFAS']._serialized_start=535
  _globals['_GERENCIARTAREFAS']._serialized_end=739
# @@protoc_insertion_point(module_scope)
